import sqlite3
db = sqlite3.connect('/data/dogs.db', detect_types=sqlite3.PARSE_DECLTYPES)
cursor = db.cursor()
cursor.execute('DROP TABLE IF EXISTS dogs')
cursor.execute('CREATE TABLE dogs (rfid INTEGER NOT NULL, adopted BOOLEAN NOT NULL, image TEXT)')
cursor.execute('INSERT INTO dogs VALUES (123456789, 0, "card1")')
cursor.execute('INSERT INTO dogs VALUES (83746E124, 0, "card2")')
cursor.execute('INSERT INTO dogs VALUES (83746E124, 0, "card3")')
cursor.execute('INSERT INTO dogs VALUES (83746E124, 1, "card4")')
cursor.execute('INSERT INTO dogs VALUES (83746E124, 1, "card5")')
cursor.execute('INSERT INTO dogs VALUES (83746E124, 0, "card6")')
cursor.close()
db.commit()
db.close()